insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','(762) 526-5961','jigrormo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','(267) 955-5124','zun')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','(680) 368-2192','capfad')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','(281) 301-2039','dec')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','(600) 616-7955','bivo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','(882) 813-1374','judbilo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','(642) 665-1763','joraf')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','(383) 458-2132','kem')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','(769) 335-6771','odeter')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','(803) 586-8035','lisohuje')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','(531) 919-2280','duod')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','(814) 667-8937','nowufpus')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','(713) 311-8766','kagu')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','(381) 421-2371','fef')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','(940) 463-7299','derwogi')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','(777) 435-9570','wehovuce')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','(517) 393-9630','zamum')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','(711) 904-3669','dunebuh')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','(935) 404-4792','repiwid')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','(935) 267-8492','razuppa')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','(763) 948-4815','kulmenim')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','(238) 240-2561','ib')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','(410) 257-1723','ba')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','(566) 726-3346','tohhij')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','(416) 906-7221','tuvo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','(611) 712-1562','foga')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','(919) 887-8542','uswuzzub')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','(982) 684-7650','hivwerip')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','(811) 931-8202','gugusu')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','(927) 400-3928','zedekak')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 31,'Jay','Blake','jay.blake@ral.mk','(365) 345-1498','ral')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','(656) 968-9869','turuhu')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','(739) 612-6585','omjo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','(485) 521-2687','rig')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','(835) 620-3330','sicewap')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','(211) 851-5960','fo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','(811) 311-5257','gegijap')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','(843) 836-3759','kuvesa')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','(913) 235-1856','lapahu')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','(467) 487-7239','zev')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','(724) 340-3634','nabeaga')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','(413) 229-8428','kaot')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','(886) 292-9749','tawuctuj')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','(418) 472-1239','eh')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','(961) 233-3461','fajjusuz')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','(605) 226-4037','pave')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','(719) 765-1705','ispaviw')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','(232) 228-5539','ha')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','(768) 554-8377','iliat')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','(311) 731-7079','do')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 51,'Richard','Silva','richard.silva@wi.lc','(207) 554-6244','wi')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','(558) 913-2855','iwage')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','(832) 759-6654','joopoju')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','(482) 736-8079','gojawu')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','(677) 345-2680','afigoh')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 56,'Lula','Testi','lula.testi@benom.tj','(610) 374-7581','benom')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','(982) 583-8067','jevakbe')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','(680) 266-3167','darhow')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','(611) 955-4652','dupid')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','(940) 714-8088','comouc')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','(868) 481-5125','igunisi')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 62,'Joe','Riley','joe.riley@pe.vu','(225) 395-2772','pe')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','(365) 837-6888','puk')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','(606) 352-8734','vegub')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','(555) 800-7339','rucwi')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','(657) 357-3671','agijit')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','(523) 789-5485','loolu')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','(766) 966-7387','tupwovali')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','(672) 613-2954','hidge')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','(803) 549-9387','liowci')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','(526) 435-1819','vesa')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','(937) 855-5936','wupikdoh')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','(960) 335-6192','dajsiphaj')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','(735) 809-2611','soofpe')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','(857) 797-7918','aruzusjas')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','(659) 331-1543','ufeco')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','(759) 639-8597','uneehi')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','(942) 352-4854','hahinaba')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 79,'Rodney','Love','rodney.love@zun.ph','(247) 867-8287','zun')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','(302) 793-9936','jo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','(861) 740-6628','goltuefo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','(953) 866-9992','lupuwuzo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','(915) 491-8384','reduzris')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','(584) 909-6235','pubsav')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','(673) 849-4256','lullip')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','(268) 208-9643','aba')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','(873) 489-6641','kettujwo')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','(243) 974-5539','ju')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','(816) 699-1291','vioburez')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','(319) 401-1090','ig')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','(359) 691-6408','omu')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','(273) 892-4646','luw')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','(304) 610-2881','pi')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 94,'Craig','Russell','craig.russell@zu.nz','(237) 969-2900','zu')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 95,'John','Sutton','john.sutton@ag.ee','(207) 424-6468','ag')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','(481) 661-8179','fopav')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 97,'Gary','Baker','gary.baker@ji.cf','(212) 510-3444','ji')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','(433) 862-3076','lojet')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','(619) 506-4452','ukve')
insert into students(version, id,first_name,last_name,email,phone,courses) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','(616) 688-6883','viipo')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 1,'jigrormo','Eula Lane','zun capfad','7','70')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 2,'zun','Barry Rodriquez','capfad dec','2','11')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 3,'capfad','Eugenia Selvi','dec bivo','6','51')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 4,'dec','Alejandro Miles','bivo judbilo','2','11')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 5,'bivo','Cora Tesi','judbilo joraf','6','53')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 6,'judbilo','Marguerite Ishii','joraf kem','9','87')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 7,'joraf','Mildred Jacobs','kem odeter','6','58')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 8,'kem','Gene Goodman','odeter lisohuje','2','15')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 9,'odeter','Lettie Bennett','lisohuje duod','7','66')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 10,'lisohuje','Mabel Leach','duod nowufpus','8','79')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 11,'duod','Jordan Miccinesi','nowufpus kagu','5','42')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 12,'nowufpus','Marie Parkes','kagu fef','9','82')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 13,'kagu','Rose Gray','fef derwogi','7','67')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 14,'fef','Garrett Stokes','derwogi wehovuce','2','16')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 15,'derwogi','Barbara Matthieu','wehovuce zamum','10','95')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 16,'wehovuce','Jean Rhodes','zamum dunebuh','8','75')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 17,'zamum','Jack Romoli','dunebuh repiwid','5','50')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 18,'dunebuh','Pearl Holden','repiwid razuppa','8','75')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 19,'repiwid','Belle Montero','razuppa kulmenim','10','92')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 20,'razuppa','Olive Molina','kulmenim ib','10','91')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 21,'kulmenim','Minerva Todd','ib ba','8','74')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 22,'ib','Bobby Pearson','ba tohhij','1','10')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 23,'ba','Larry Ciappi','tohhij tuvo','3','29')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 24,'tohhij','Ronnie Salucci','tuvo foga','5','50')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 25,'tuvo','Walter Grossi','foga uswuzzub','4','37')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 26,'foga','Frances Koopmans','uswuzzub hivwerip','6','58')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 27,'uswuzzub','Frances Fujimoto','hivwerip gugusu','9','89')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 28,'hivwerip','Olivia Vidal','gugusu zedekak','10','91')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 29,'gugusu','Edna Henry','zedekak ral','8','77')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 30,'zedekak','Lydia Brun','ral turuhu','10','95')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 31,'ral','Jay Blake','turuhu omjo','2','15')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 32,'turuhu','Isabel Serafini','omjo rig','6','51')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 33,'omjo','Rebecca Carter','rig sicewap','7','66')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 34,'rig','Maurice Fabbrini','sicewap fo','4','32')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 35,'sicewap','Ollie Turnbull','fo gegijap','8','80')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 36,'fo','Jerry Hopkins','gegijap kuvesa','1','10')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 37,'gegijap','Nora Lyons','kuvesa lapahu','8','79')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 38,'kuvesa','Anne Weiß','lapahu zev','9','84')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 39,'lapahu','Louise Gauthier','zev nabeaga','10','95')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 40,'zev','Lloyd Fani','nabeaga kaot','4','33')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 41,'nabeaga','Maud Dunn','kaot tawuctuj','7','69')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 42,'kaot','Henry Gigli','tawuctuj eh','4','36')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 43,'tawuctuj','Virgie Werner','eh fajjusuz','9','83')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 44,'eh','Gregory Cozzi','fajjusuz pave','3','30')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 45,'fajjusuz','Lucinda Gil','pave ispaviw','9','90')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 46,'pave','Gertrude Verbeek','ispaviw ha','6','60')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 47,'ispaviw','Mattie Graham','ha iliat','7','67')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 48,'ha','Bryan Shaw','iliat do','1','6')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 49,'iliat','Essie Adams','do wi','7','66')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 50,'do','Gary Osborne','wi iwage','2','15')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 51,'wi','Richard Silva','iwage joopoju','1','10')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 52,'iwage','Dustin Pestelli','joopoju gojawu','5','47')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 53,'joopoju','Henrietta Hilton','gojawu afigoh','9','81')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 54,'gojawu','Francisco Giordano','afigoh benom','4','36')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 55,'afigoh','Cynthia Sardi','benom jevakbe','6','51')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 56,'benom','Lula Testi','jevakbe darhow','6','53')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 57,'jevakbe','Bess Lucas','darhow dupid','10','96')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 58,'darhow','Linnie Driessen','dupid comouc','6','57')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 59,'dupid','Eva Tesi','comouc igunisi','6','53')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 60,'comouc','Augusta Sakai','igunisi pe','9','88')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 61,'igunisi','Mathilda Schwarz','pe puk','9','83')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 62,'pe','Joe Riley','puk vegub','1','7')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 63,'puk','Leon McGee','vegub rucwi','2','14')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 64,'vegub','Florence Viviani','rucwi agijit','6','55')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 65,'rucwi','Lee Miceli','agijit loolu','5','43')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 66,'agijit','Celia Sodi','loolu tupwovali','6','52')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 67,'loolu','Aaron Misuri','tupwovali hidge','5','43')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 68,'tupwovali','Fanny Parkinson','hidge liowci','8','75')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 69,'hidge','Phoebe Vitale','liowci vesa','6','55')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 70,'liowci','Edith Brennan','vesa wupikdoh','8','76')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 71,'vesa','Jeremy Marilli','wupikdoh dajsiphaj','5','41')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 72,'wupikdoh','Kathryn Huet','dajsiphaj soofpe','10','97')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 73,'dajsiphaj','Lelia Matsuo','soofpe aruzusjas','9','89')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 74,'soofpe','Virginia Woods','aruzusjas ufeco','7','69')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 75,'aruzusjas','Sally Aoki','ufeco uneehi','9','87')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 76,'ufeco','Isabelle de Ridder','uneehi hahinaba','7','61')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 77,'uneehi','Rosie Murphy','hahinaba zun','7','66')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 78,'hahinaba','Lou Meyer','zun jo','10','95')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 79,'zun','Rodney Love','jo goltuefo','2','12')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 80,'jo','Kenneth Bianchini','goltuefo lupuwuzo','3','23')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 81,'goltuefo','Essie Dietrich','lupuwuzo reduzris','9','85')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 82,'lupuwuzo','Leila Simon','reduzris pubsav','10','94')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 83,'reduzris','Eva Pierre','pubsav lullip','10','97')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 84,'pubsav','Landon Moretti','lullip aba','5','43')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 85,'lullip','Mittie Sardi','aba kettujwo','6','51')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 86,'aba','Corey McDaniel','kettujwo ju','2','12')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 87,'kettujwo','Hester Stein','ju vioburez','9','85')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 88,'ju','Danny Lowe','vioburez ig','1','10')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 89,'vioburez','Lillie Winter','ig omu','8','79')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 90,'ig','Brandon Borchi','omu luw','3','24')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 91,'omu','Isaac Bernardi','luw pi','3','22')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 92,'luw','Clyde Crawford','pi zu','1','5')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 93,'pi','Paul Sherman','zu ag','2','16')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 94,'zu','Craig Russell','ag fopav','1','4')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 95,'ag','John Sutton','fopav ji','2','11')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 96,'fopav','Francisco Formigli','ji lojet','4','34')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 97,'ji','Gary Baker','lojet ukve','1','2')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 98,'lojet','Earl Giovannoni','ukve viipo','4','37')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 99,'ukve','Helen Zanieri','viipo apuwibem','6','55')
insert into courses(version, id,name,teacher,about,difficulty,student_count) values (1, 100,'viipo','Agnes Toccafondi','apuwibem nine','6','53')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','(762) 526-5961','jigrormo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','(267) 955-5124','zun')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','(680) 368-2192','capfad')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','(281) 301-2039','dec')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','(600) 616-7955','bivo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','(882) 813-1374','judbilo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','(642) 665-1763','joraf')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','(383) 458-2132','kem')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','(769) 335-6771','odeter')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','(803) 586-8035','lisohuje')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','(531) 919-2280','duod')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','(814) 667-8937','nowufpus')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','(713) 311-8766','kagu')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','(381) 421-2371','fef')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','(940) 463-7299','derwogi')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','(777) 435-9570','wehovuce')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','(517) 393-9630','zamum')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','(711) 904-3669','dunebuh')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','(935) 404-4792','repiwid')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','(935) 267-8492','razuppa')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','(763) 948-4815','kulmenim')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','(238) 240-2561','ib')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','(410) 257-1723','ba')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','(566) 726-3346','tohhij')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','(416) 906-7221','tuvo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','(611) 712-1562','foga')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','(919) 887-8542','uswuzzub')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','(982) 684-7650','hivwerip')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','(811) 931-8202','gugusu')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','(927) 400-3928','zedekak')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 31,'Jay','Blake','jay.blake@ral.mk','(365) 345-1498','ral')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','(656) 968-9869','turuhu')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','(739) 612-6585','omjo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','(485) 521-2687','rig')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','(835) 620-3330','sicewap')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','(211) 851-5960','fo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','(811) 311-5257','gegijap')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','(843) 836-3759','kuvesa')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','(913) 235-1856','lapahu')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','(467) 487-7239','zev')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','(724) 340-3634','nabeaga')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','(413) 229-8428','kaot')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','(886) 292-9749','tawuctuj')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','(418) 472-1239','eh')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','(961) 233-3461','fajjusuz')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','(605) 226-4037','pave')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','(719) 765-1705','ispaviw')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','(232) 228-5539','ha')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','(768) 554-8377','iliat')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','(311) 731-7079','do')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 51,'Richard','Silva','richard.silva@wi.lc','(207) 554-6244','wi')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','(558) 913-2855','iwage')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','(832) 759-6654','joopoju')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','(482) 736-8079','gojawu')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','(677) 345-2680','afigoh')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 56,'Lula','Testi','lula.testi@benom.tj','(610) 374-7581','benom')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','(982) 583-8067','jevakbe')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','(680) 266-3167','darhow')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','(611) 955-4652','dupid')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','(940) 714-8088','comouc')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','(868) 481-5125','igunisi')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 62,'Joe','Riley','joe.riley@pe.vu','(225) 395-2772','pe')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','(365) 837-6888','puk')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','(606) 352-8734','vegub')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','(555) 800-7339','rucwi')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','(657) 357-3671','agijit')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','(523) 789-5485','loolu')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','(766) 966-7387','tupwovali')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','(672) 613-2954','hidge')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','(803) 549-9387','liowci')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','(526) 435-1819','vesa')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','(937) 855-5936','wupikdoh')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','(960) 335-6192','dajsiphaj')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','(735) 809-2611','soofpe')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','(857) 797-7918','aruzusjas')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','(659) 331-1543','ufeco')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','(759) 639-8597','uneehi')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','(942) 352-4854','hahinaba')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 79,'Rodney','Love','rodney.love@zun.ph','(247) 867-8287','zun')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','(302) 793-9936','jo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','(861) 740-6628','goltuefo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','(953) 866-9992','lupuwuzo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','(915) 491-8384','reduzris')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','(584) 909-6235','pubsav')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','(673) 849-4256','lullip')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','(268) 208-9643','aba')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','(873) 489-6641','kettujwo')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','(243) 974-5539','ju')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','(816) 699-1291','vioburez')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','(319) 401-1090','ig')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','(359) 691-6408','omu')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','(273) 892-4646','luw')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','(304) 610-2881','pi')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 94,'Craig','Russell','craig.russell@zu.nz','(237) 969-2900','zu')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 95,'John','Sutton','john.sutton@ag.ee','(207) 424-6468','ag')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','(481) 661-8179','fopav')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 97,'Gary','Baker','gary.baker@ji.cf','(212) 510-3444','ji')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','(433) 862-3076','lojet')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','(619) 506-4452','ukve')
insert into teachers(version, id,first_name,last_name,email,phone,courses) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','(616) 688-6883','viipo')
